/*
 * Licensed under the EUPL-1.2-or-later.
 * Copyright (c) 2020, gridDigIt Kft. All rights reserved.
 */
package eu.griddigit.cimpal.core.kgcl;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * Serializes a list of {@link KgclChange} to the KGCL Controlled Natural Language (CNL), the
 * human-readable one-statement-per-line syntax (e.g. {@code rename cim:Foo from "X" to "Y"}).
 * <p>
 * The exact verbs follow the KGCL CNL grammar; facets that were only added or only removed (rather
 * than changed) degrade to the closest {@code add}/{@code remove}/{@code set} form.
 */
public class KgclCnlWriter {

    /** Renders the changes as CNL text. */
    public String toCnl(List<KgclChange> changes) {
        StringBuilder sb = new StringBuilder();
        sb.append("# KGCL changeset generated by CimPal\n");
        for (KgclChange change : changes) {
            sb.append(toStatement(change)).append('\n');
        }
        return sb.toString();
    }

    /** Writes the CNL text (UTF-8) to the given stream. The stream is not closed. */
    public void write(OutputStream outputStream, List<KgclChange> changes) throws IOException {
        Writer writer = new BufferedWriter(new OutputStreamWriter(outputStream, StandardCharsets.UTF_8));
        writer.write(toCnl(changes));
        writer.flush();
    }

    private static String toStatement(KgclChange c) {
        String id = c.getAboutNode();
        String prop = c.getProperty();
        String oldV = c.getOldValue();
        String newV = c.getNewValue();

        return switch (c.getType()) {
            case NODE_CREATION -> newV != null
                    ? "create node " + id + " " + quote(newV)
                    : "create node " + id;
            case NODE_DELETION -> "delete node " + id;
            case NODE_RENAME -> {
                if (oldV != null && newV != null) {
                    yield "rename " + id + " from " + quote(oldV) + " to " + quote(newV);
                } else if (newV != null) {
                    yield "set label of " + id + " to " + quote(newV);
                } else {
                    yield "remove label of " + id;
                }
            }
            case NODE_DEFINITION_CHANGE -> {
                if (oldV != null && newV != null) {
                    yield "change definition of " + id + " from " + quote(oldV) + " to " + quote(newV);
                } else if (newV != null) {
                    yield "add definition " + quote(newV) + " to " + id;
                } else {
                    yield "remove definition for " + id;
                }
            }
            case NODE_MOVE -> {
                // subClassOf targets are node identifiers, emitted unquoted
                if (oldV != null && newV != null) {
                    yield "move " + id + " from " + oldV + " to " + newV;
                } else if (newV != null) {
                    yield "create edge " + id + " rdfs:subClassOf " + newV;
                } else {
                    yield "delete edge " + id + " rdfs:subClassOf " + oldV;
                }
            }
            case NODE_ANNOTATION_CHANGE -> {
                String facet = prop == null ? "annotation" : prop;
                if (oldV != null && newV != null) {
                    yield "change " + facet + " of " + id + " from " + quote(oldV) + " to " + quote(newV);
                } else if (newV != null) {
                    yield "set " + facet + " of " + id + " to " + quote(newV);
                } else {
                    yield "remove " + facet + " of " + id;
                }
            }
        };
    }

    /** Wraps a literal value in double quotes, escaping backslashes and embedded quotes. */
    private static String quote(String value) {
        String escaped = value.replace("\\", "\\\\").replace("\"", "\\\"");
        return "\"" + escaped + "\"";
    }
}
