<#
 Copyright (c) 2020-2026 gridDigIt Kft.
 Licensed under the EUPL-1.2-or-later.
 SPDX-License-Identifier: EUPL-1.2+
#>
<#
.SYNOPSIS
    Records the coverage ratchet floors. For each module it reads the JaCoCo report
    (<module>/target/site/jacoco/jacoco.csv, written by `mvn verify`) and writes
    <module>/coverage-baseline.properties with
        coverage.line.min   = measured line ratio   - Margin (floored to 4 decimals)
        coverage.branch.min = measured branch ratio - Margin (floored to 4 decimals)
    The parent pom's jacoco `check` fails `verify` when coverage drops below them.

    Floors only go up. A floor that would drop is kept unless -AllowDecrease is given
    (use it only when coverage fell for an agreed reason, and say why in the commit).

.EXAMPLE
    mvn -B verify
    ./scripts/Update-CoverageBaseline.ps1
    ./scripts/Update-CoverageBaseline.ps1 -Modules CimPal-Core -AllowDecrease
#>
param(
    [string[]]$Modules = @("CimPal-Core", "CimPal-Main", "CimPal-CLI"),
    [double]$Margin = 0.005,
    [switch]$AllowDecrease
)

$ErrorActionPreference = "Stop"

$repoRoot = git rev-parse --show-toplevel
$inv = [System.Globalization.CultureInfo]::InvariantCulture

function Get-Floor([double]$ratio) {
    [Math]::Max(0.0, [Math]::Floor(($ratio - $Margin) * 10000) / 10000)
}

function Read-ExistingFloor([string]$file, [string]$key) {
    if (-not (Test-Path $file)) { return $null }
    $line = Get-Content $file | Where-Object { $_ -match "^\s*$([regex]::Escape($key))\s*=" } | Select-Object -First 1
    if (-not $line) { return $null }
    [double]::Parse(($line -split "=", 2)[1].Trim(), $inv)
}

foreach ($module in $Modules) {
    $csv = Join-Path $repoRoot "$module\target\site\jacoco\jacoco.csv"
    if (-not (Test-Path $csv)) {
        Write-Warning "$module has no JaCoCo report ($csv). Run 'mvn -B verify' first. Skipped."
        continue
    }

    $rows = Import-Csv $csv
    $lineCovered   = ($rows | Measure-Object LINE_COVERED   -Sum).Sum
    $lineMissed    = ($rows | Measure-Object LINE_MISSED    -Sum).Sum
    $branchCovered = ($rows | Measure-Object BRANCH_COVERED -Sum).Sum
    $branchMissed  = ($rows | Measure-Object BRANCH_MISSED  -Sum).Sum

    $lineRatio   = if ($lineCovered + $lineMissed) { $lineCovered / ($lineCovered + $lineMissed) } else { 0.0 }
    $branchRatio = if ($branchCovered + $branchMissed) { $branchCovered / ($branchCovered + $branchMissed) } else { 0.0 }

    $out = Join-Path $repoRoot "$module\coverage-baseline.properties"
    $floors = @{}
    foreach ($entry in @(@("coverage.line.min", $lineRatio), @("coverage.branch.min", $branchRatio))) {
        $key, $ratio = $entry
        $new = Get-Floor $ratio
        $old = Read-ExistingFloor $out $key
        if ($null -ne $old -and $new -lt $old -and -not $AllowDecrease) {
            Write-Warning "$module ${key}: measured floor $($new.ToString('0.0000', $inv)) is below the recorded $($old.ToString('0.0000', $inv)); keeping the recorded floor (use -AllowDecrease to lower it)."
            $new = $old
        }
        $floors[$key] = $new
    }

    $content = @(
        "# Copyright (c) 2020-2026 gridDigIt Kft.",
        "# Licensed under the EUPL-1.2-or-later.",
        "# SPDX-License-Identifier: EUPL-1.2+",
        "#",
        "# Coverage ratchet floors for $module, read by the parent pom's jacoco check.",
        "# Generated by scripts/Update-CoverageBaseline.ps1. Do not lower by hand.",
        "# Measured: line $($lineRatio.ToString('0.0000', $inv)) ($lineCovered/$($lineCovered + $lineMissed)), branch $($branchRatio.ToString('0.0000', $inv)) ($branchCovered/$($branchCovered + $branchMissed))",
        "coverage.line.min=$($floors['coverage.line.min'].ToString('0.0000', $inv))",
        "coverage.branch.min=$($floors['coverage.branch.min'].ToString('0.0000', $inv))"
    )
    Set-Content -Path $out -Value $content -Encoding ascii
    Write-Host ("{0}: line {1:P2} -> min {2}, branch {3:P2} -> min {4}" -f $module, $lineRatio,
        $floors['coverage.line.min'].ToString('0.0000', $inv), $branchRatio, $floors['coverage.branch.min'].ToString('0.0000', $inv))
}
