# Copyright (c) 2020-2026 gridDigIt Kft.
# Licensed under the EUPL-1.2-or-later.
# SPDX-License-Identifier: EUPL-1.2+
apiVersion: v1
kind: Namespace
metadata:
  name: cimpal
  labels:
    # The pod meets the "restricted" Pod Security Standard.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
