# Copyright (c) 2020-2026 gridDigIt Kft.
# Licensed under the EUPL-1.2-or-later.
# SPDX-License-Identifier: EUPL-1.2+
# Filled in by Maven resource filtering (see CimPal-CLI/pom.xml) and read by CliVersion.
version=${project.version}
